name             = "Muscade"
uuid             = "93488820-1883-11ed-0c34-05177b029e4d"
authors          = ["Philippe Maincon <philippe.maincon@sintef.no>"]
version          = "0.3.5"

[deps]
LinearAlgebra    = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MacroTools       = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
Printf           = "de0858da-6303-5e67-8744-51eddeeeb8d7"
SparseArrays     = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
StaticArrays     = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
julia            = "1.8"
SpecialFunctions = "2.2"
StaticArrays     = "1.5"
MacroTools       = "0.5.10"

